# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake
#permissions: 
#  contents: write

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - name: Checkout Repository      
        uses: actions/checkout@v3
      
      - name: Generate GitHub Contributions Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next line generate the files on a branch called "output". This keeps the main branch from cluttering up.
          outputs:
            dist/github-snake.svg
                     
      - name: Deploy to GitHub Pages         
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
